sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: regions
      - name: nations
      - name: v_nations
      - name: nation_info
      - name: orders
      - name: lineitems
      - name: parts
      - name: suppliers

      - name: partsupps
        config:
          freshness:
            warn_after: {count: 1,period: hour}
            error_after: {count: 1,period: hour}
          loaded_at_field: o_orderdate::timestamp_ntz


